export const marqueeItems = [
  "Angular",
  "TypeScript",
  "RxJS",
  "NgRx",
  "Ionic",
  "React Native",
  "JavaScript",
  "Core Java",
  "Python",
  "Node.js",
  "Express.js",
  "Capacitor",
  "REST API",
  "PostgreSQL",
  "Mobile Apps",
] as const;
